version: '3.9'
services:
  s3-bucket:
    build: ./s3server
    restart: always
    ports:
      - 9000:9000
    command: 'node ./s3server/s3.mjs'
    environment:
      AWS_ACCESS_KEY_ID: S3RVER
      AWS_SECRET_ACCESS_KEY: S3RVER
    volumes:
      - './:/home/app'
